Práctica semana 2

Cargar CSV

In [17]:
import pandas as pd
dat_csv = pd.read_csv(r"C:\Users\barby\OneDrive\Escritorio\Barby\Cs de Datos 2026\Aprendizaje Automático\archivos semana 2\ventas (1).csv", encoding = "ISO-8859-1")
dat_csv

   id_venta       fecha  producto  cantidad  precio_unitario
0         1  2026-01-10  Notebook         2             1200
1         2  2026-01-12     Mouse         5               25
2         3  2026-01-15   Teclado         3               45
3         4  2026-01-18   Monitor         1              300

Restringir la salida a las 5 primeras filas con metodo "Head()".

In [10]:
dat_csv.head()

   id_venta       fecha  producto  cantidad  precio_unitario
0         1  2026-01-10  Notebook         2             1200
1         2  2026-01-12     Mouse         5               25
2         3  2026-01-15   Teclado         3               45
3         4  2026-01-18   Monitor         1              300

En los dos casos anteriores, aparecen los elementos de la primera fila como los nombres de las columnas de datos, si no quisiéramos este comportamiento podemos agregar el atributo header = None, de la siguiente manera:

In [12]:
dat_csv = pd.read_csv(
	r"C:\Users\barby\OneDrive\Escritorio\Barby\Cs de Datos 2026\Aprendizaje Automático\archivos semana 2\ventas (1).csv",
	encoding="ISO-8859-1",
	header=None
)
dat_csv

          0           1         2         3                4
0  id_venta       fecha  producto  cantidad  precio_unitario
1         1  2026-01-10  Notebook         2             1200
2         2  2026-01-12     Mouse         5               25
3         3  2026-01-15   Teclado         3               45
4         4  2026-01-18   Monitor         1              300

Si quisiéramos que tomar una determinada línea como cabecera, debemos asignarle al parámetro header el número de fila correspondiente, en el siguiente ejemplo se toma la línea 3 como cabecera:

In [13]:
dat_csv = pd.read_csv(
	r"C:\Users\barby\OneDrive\Escritorio\Barby\Cs de Datos 2026\Aprendizaje Automático\archivos semana 2\ventas (1).csv",
	encoding="ISO-8859-1",
	header= 3)
dat_csv

   3  2026-01-15  Teclado  3.1   45
0  4  2026-01-18  Monitor    1  300

Por defecto, read_csv asigna un índice numérico predeterminado que comienza con cero al leer los datos. Sin embargo, es posible alterar este comportamiento pasando el nombre de la columna que utilizaremos como índice. A continuación se dejara la columna id como índice de la tabla:

In [19]:
dat_csv = pd.read_csv(
    r"C:\Users\barby\OneDrive\Escritorio\Barby\Cs de Datos 2026\Aprendizaje Automático\archivos semana 2\ventas (1).csv",
	encoding="ISO-8859-1",
	index_col='id_venta')
dat_csv

               fecha  producto  cantidad  precio_unitario
id_venta
1         2026-01-10  Notebook         2             1200
2         2026-01-12     Mouse         5               25
3         2026-01-15   Teclado         3               45
4         2026-01-18   Monitor         1              300

En el caso de que queramos restringir la tabla a algunas columnas específicas, podemos realizarlo con el parámetro usecols indicando en una lista las columnas seleccionadas.

In [21]:
dat_csv = pd.read_csv(
    r"C:\Users\barby\OneDrive\Escritorio\Barby\Cs de Datos 2026\Aprendizaje Automático\archivos semana 2\ventas (1).csv",
	encoding="ISO-8859-1",
    usecols={'producto', 'cantidad'})
dat_csv.head()

   producto  cantidad
0  Notebook         2
1     Mouse         5
2   Teclado         3
3   Monitor         1

Nota: Si alguna de las líneas se encuentra en blanco, podemos eliminar dichas líneas mediante el atributo skip_blank_lines=False
Si queremos eliminar una fila en particular, podemos utilizar el parámetro skiprows, en el siguiente caso se eliminan las filas 1 y 4:

In [22]:
dat_csv = pd.read_csv(
    r"C:\Users\barby\OneDrive\Escritorio\Barby\Cs de Datos 2026\Aprendizaje Automático\archivos semana 2\ventas (1).csv",
	encoding="ISO-8859-1",
    skiprows= [1,4])
dat_csv.head()

   id_venta       fecha producto  cantidad  precio_unitario
0         2  2026-01-12    Mouse         5               25
1         3  2026-01-15  Teclado         3               45

Para presentar un número dado de filas desde el inicio, podemos utilizar el parámetro nrows, en el siguiente ejemplo se presentan las primeras tres filas de datos.

In [23]:
dat_csv = pd.read_csv(
    r"C:\Users\barby\OneDrive\Escritorio\Barby\Cs de Datos 2026\Aprendizaje Automático\archivos semana 2\ventas (1).csv",
	encoding="ISO-8859-1",
    nrows=3)
dat_csv.head()

   id_venta       fecha  producto  cantidad  precio_unitario
0         1  2026-01-10  Notebook         2             1200
1         2  2026-01-12     Mouse         5               25
2         3  2026-01-15   Teclado         3               45

Para seleccionar un rango específico de filas podemos utilizar el método query especificando los límites aplicables sobre una determinada columna:

In [24]:
dat_csv = pd.read_csv(
    r"C:\Users\barby\OneDrive\Escritorio\Barby\Cs de Datos 2026\Aprendizaje Automático\archivos semana 2\ventas (1).csv",
	encoding="ISO-8859-1")
dat_csv.query('2<= cantidad <= 4')

   id_venta       fecha  producto  cantidad  precio_unitario
0         1  2026-01-10  Notebook         2             1200
2         3  2026-01-15   Teclado         3               45

Importar desde Excel

En el caso de trabajar directamente con un archivo de Excel, podemos utilizar el método read_excel() de forma análoga a como lo hicimos anteriormente con read_csv()

In [26]:
import pandas as pd
dat_excel = pd.read_excel(r"C:\Users\barby\OneDrive\Escritorio\Barby\Cs de Datos 2026\Aprendizaje Automático\archivos semana 2\inventario.xlsx")
dat_excel.head()

   id_producto    nombre    categoria  stock  precio
0            1  Notebook  Electrónica     10    1200
1            2     Mouse   Accesorios     50      25
2            3   Teclado   Accesorios     30      45
3            4   Monitor  Electrónica     15     300

Nota: El parámetro sheetname nos permite seleccionar el número de hoja, las cuales se comienzan a numerar desde cero.

Formato JSON

In [27]:
import pandas as pd
movies_json = pd.read_json(r"C:\Users\barby\OneDrive\Escritorio\Barby\Cs de Datos 2026\Aprendizaje Automático\archivos semana 2\clientes.json")
movies_json.head()

   id_cliente        nombre             email   telefono
0           1    Juan Pérez    juan@email.com  123456789
1           2   María López   maria@email.com  987654321
2           3  Carlos Gómez  carlos@email.com  456123789